import pandas as pd

# Input fil
input_file_path = 'C:\\Users\\vetle\\OneDrive\\Dokumenter\\Skole\\BigData\\noder\\psam_ca2.csv'
output_file_path = 'psam_ca2_converted.csv'  # Output fil

# Kolonner som skal beholdes
columns_to_keep = ['education_level_id', 'current_education_id', 'poverty_income_ratio', 'when_last_worked_id', 'field_of_degree1_id', 'field_of_degree2_id', 'age', 'sex_id', 'sallary_past_12_months', 'total_persons_earnings']


# Verdier som skal konverteres til tekst 
education_level = {
    4: 'Grade 1',
    1: 'No schooling completed',
    7: 'Grade 4',
    16: 'Regular high school diploma',
    3: 'Kindergarten',
    23: 'Professional degree beyond a bachelor\'s degree',
    10: 'Grade 7',
    19: '1 or more years of college credit, no degree',
    22: 'Master\'s degree',
    20: 'Associate\'s degree',
    0: 'N/A (less than 3 years old)',
    2: 'Nursery school, preschool',
    21: 'Bachelor\'s degree',
    8: 'Grade 5',
    24: 'Doctorate degree',
    14: 'Grade 11',
    6: 'Grade 3',
    17: 'GED or alternative credential',
    12: 'Grade 9',
    13: 'Grade 10',
    9: 'Grade 6',
    5: 'Grade 2',
    15: '12th grade - no diploma',
    11: 'Grade 8',
    18: 'Some college, but less than 1 year'
}

current_education = {
    15: 'College undergraduate years (freshman to senior)',
    11: 'Grade 9',
    1: 'Nursery school/preschool',
    7: 'Grade 5',
    5: 'Grade 3',
    14: 'Grade 12',
    13: 'Grade 11',
    9: 'Grade 7',
    3: 'Grade 1',
    8: 'Grade 6',
    6: 'Grade 4',
    16: 'Graduate or professional school beyond a bachelor\'s degree',
    10: 'Grade 8',
    0: 'N/A (not attending school)',
    4: 'Grade 2',
    2: 'Kindergarten',
    12: 'Grade 10'
}


field_of_degree1 = {
    6110: 'Community And Public Health',
    2300: 'General Education',
    6105: 'Medical Technologies Technicians',
    6000: 'Fine Arts',
    1106: 'Soil Science',
    2314: 'Art And Music Education',
    2313: 'Language And Drama Education',
    3402: 'Humanities',
    2312: 'Teacher Education: Multiple Levels',
    2310: 'Special Needs Education',
    5200: 'Psychology',
    4901: 'Theology And Religious Vocations',
    4000: 'Multi/Interdisciplinary Studies',
    3302: 'Composition And Rhetoric',
    4006: 'Cognitive Science And Biopsychology',
    2901: 'Family And Consumer Sciences',
    5500: 'General Social Sciences',
    5501: 'Economics',
    3609: 'Zoology',
    5901: 'Transportation Sciences And Technologies',
    5001: 'Astronomy And Astrophysics',
    6207: 'Finance',
    2409: 'Engineering Mechanics Physics And Science',
    6102: 'Communication Disorders Sciences And Services',
    5005: 'Geosciences',
    2301: 'Educational Administration And Supervision',
    5701: 'Electrical, Mechanical, And Precision Technologies And Production',
    6099: 'Miscellaneous Fine Arts',
    5201: 'Educational Psychology',
    6007: 'Studio Arts',
    6403: 'United States History',
    4001: 'Intercultural And International Studies',
    3700: 'Mathematics',
    2501: 'Engineering And Industrial Management',
    4007: 'Interdisciplinary Social Sciences',
    3603: 'Molecular Biology',
    3202: 'Pre-Law And Legal Studies',
    2404: 'Biomedical Engineering',
    2403: 'Architectural Engineering',
    2412: 'Industrial And Manufacturing Engineering',
    2411: 'Geological And Geophysical Engineering',
    4002: 'Nutrition Sciences',
    1401: 'Architecture',
    3301: 'English Language And Literature',
    4801: 'Philosophy And Religious Studies',
    6200: 'General Business',
    5506: 'Political Science And Government',
    6210: 'International Business',
    6212: 'Management Information Systems And Statistics',
    6211: 'Hospitality Management',
    5004: 'Geology And Earth Science',
    2401: 'Aerospace Engineering',
    2408: 'Electrical Engineering',
    2413: 'Materials Engineering And Materials Science',
    5401: 'Public Administration',
    5402: 'Public Policy',
    5403: 'Human Services And Community Organization',
    2418: 'Nuclear Engineering',
    2306: 'Physical And Health Education Teaching',
    2304: 'Elementary Education',
    6109: 'Treatment Therapy Professions',
    6003: 'Visual And Performing Arts',
    6004: 'Commercial Art And Graphic Design',
    1901: 'Communications',
    5202: 'Clinical Psychology',
    2601: 'Linguistics And Comparative Language And Literature',
    3702: 'Statistics And Decision Science',
    4005: 'Mathematics And Computer Science',
    3601: 'Biochemical Sciences',
    3608: 'Physiology',
    5505: 'International Relations',
    5000: 'Physical Sciences',
    2402: 'Biological Engineering',
    2400: 'General Engineering',
    5599: 'Miscellaneous Social Sciences',
    6209: 'Human Resources And Personnel Management',
    2407: 'Computer Engineering',
    5006: 'Oceanography',
    5008: 'Materials Science',
    2419: 'Petroleum Engineering',
    6199: 'Miscellaneous Health Medical Professions',
    2303: 'School Student Counseling',
    1103: 'Animal Sciences',
    2311: 'Social Science Or History Teacher Education',
    3801: 'Military Technologies',
    2603: 'Other Foreign Languages',
    5102: 'Nuclear, Industrial Radiology, And Biological Technologies',
    2503: 'Industrial Production Technologies',
    2105: 'Information Sciences',
    2500: 'Engineering Technologies',
    2101: 'Computer Programming And Data Processing',
    6203: 'Business Management And Administration',
    3602: 'Botany',
    5502: 'Anthropology And Archeology',
    5503: 'Criminology',
    3607: 'Pharmacology',
    5002: 'Atmospheric Sciences And Meteorology',
    5003: 'Chemistry',
    2405: 'Chemical Engineering',
    6100: 'General Medical And Health Services',
    6103: 'Health And Medical Administrative Services',
    2415: 'Metallurgical Engineering',
    6106: 'Health And Medical Preparatory Programs',
    6107: 'Nursing',
    2308: 'Science And Computer Teacher Education',
    6002: 'Music',
    1104: 'Food Science',
    2399: 'Miscellaneous Education',
    1100: 'General Agriculture',
    2201: 'Cosmetology Services And Culinary Arts',
    6402: 'History',
    2100: 'Computer And Information Systems',
    5205: 'Industrial And Organizational Psychology',
    2102: 'Computer Science',
    3604: 'Ecology',
    1302: 'Forestry',
    5504: 'Geography',
    3605: 'Genetics',
    6204: 'Operations Logistics And E-Commerce',
    2406: 'Civil Engineering',
    5098: 'Multi-Disciplinary Or General Science',
    2416: 'Mining And Mineral Engineering',
    2414: 'Mechanical Engineering',
    2499: 'Miscellaneous Engineering',
    5301: 'Criminal Justice And Fire Protection',
    2305: 'Mathematics Teacher Education',
    6108: 'Pharmacy Pharmaceutical Sciences And Administration',
    2309: 'Secondary Teacher Education',
    2307: 'Early Childhood Education',
    6001: 'Drama And Theater Arts',
    1105: 'Plant Science And Agronomy',
    1102: 'Agricultural Economics',
    1101: 'Agriculture Production And Management',
    1902: 'Journalism',
    0: 'N/A (less than bachelor\'s degree)',
    2602: 'French German Latin And Other Common Foreign Language Studies',
    5206: 'Social Psychology',
    3701: 'Applied Mathematics',
    6201: 'Accounting',
    6202: 'Actuarial Science',
    2001: 'Communication Technologies',
    1301: 'Environmental Science',
    2599: 'Miscellaneous Engineering Technologies',
    3600: 'Biology',
    3606: 'Microbiology',
    5507: 'Sociology',
    6299: 'Miscellaneous Business and Medical Administration',
    6104: 'Medical Assisting Services',
    3501: 'Library Science',
    2410: 'Environmental Engineering',
    5007: 'Physics',
    5404: 'Social Work',
    2417: 'Naval Architecture And Marine Engineering',
    4101: 'Physical Fitness Parks Recreation And Leisure',
    6005: 'Film Video And Photographic Arts',
    1501: 'Area Ethnic And Civilization Studies',
    3401: 'Liberal Arts',
    1904: 'Advertising And Public Relations',
    1903: 'Mass Media',
    1199: 'Miscellaneous Agriculture',
    6006: 'Art History And Criticism',
    5299: 'Miscellaneous Psychology',
    5203: 'Counseling Psychology',
    5601: 'Construction Services',
    2504: 'Mechanical Engineering Related Technologies',
    2107: 'Computer Networking And Telecommunications',
    2106: 'Computer Administration Management And Security',
    2502: 'Electrical Engineering Technology',
    1303: 'Natural Resources Management',
    3611: 'Neuroscience',
    6205: 'Business Economics',
    3699: 'Miscellaneous Biology',
    6206: 'Marketing And Marketing Research'
}

field_of_degree2 = {
    1903: 'Mass Media',
    4000: 'Multi/Interdisciplinary Studies',
    1401: 'Architecture',
    5205: 'Industrial And Organizational Psychology',
    2105: 'Information Sciences',
    2101: 'Computer Programming And Data Processing',
    6203: 'Business Management And Administration',
    3603: 'Molecular Biology',
    1303: 'Natural Resources Management',
    5506: 'Political Science And Government',
    5599: 'Miscellaneous Social Sciences',
    6204: 'Operations Logistics And E-Commerce',
    6206: 'Marketing And Marketing Research',
    2408: 'Electrical Engineering',
    2412: 'Industrial And Manufacturing Engineering',
    2411: 'Geological And Geophysical Engineering',
    2300: 'General Education',
    1102: 'Agricultural Economics',
    2399: 'Miscellaneous Education',
    5202: 'Clinical Psychology',
    2603: 'Other Foreign Languages',
    2602: 'French German Latin And Other Common Foreign Language Studies',
    4001: 'Intercultural And International Studies',
    2500: 'Engineering Technologies',
    4006: 'Cognitive Science And Biopsychology',
    6201: 'Accounting',
    5500: 'General Social Sciences',
    5504: 'Geography',
    5507: 'Sociology',
    5003: 'Chemistry',
    2403: 'Architectural Engineering',
    6100: 'General Medical And Health Services',
    2415: 'Metallurgical Engineering',
    2414: 'Mechanical Engineering',
    3501: 'Library Science',
    5403: 'Human Services And Community Organization',
    5404: 'Social Work',
    2400: 'General Engineering',
    2306: 'Physical And Health Education Teaching',
    4101: 'Physical Fitness Parks Recreation And Leisure',
    3401: 'Liberal Arts',
    3302: 'Composition And Rhetoric',
    3301: 'English Language And Literature',
    3700: 'Mathematics',
    4801: 'Philosophy And Religious Studies',
    2901: 'Family And Consumer Sciences',
    6202: 'Actuarial Science',
    3600: 'Biology',
    5501: 'Economics',
    2401: 'Aerospace Engineering',
    2410: 'Environmental Engineering',
    5007: 'Physics',
    2303: 'School Student Counseling',
    6107: 'Nursing',
    6003: 'Visual And Performing Arts',
    2314: 'Art And Music Education',
    5701: 'Electrical, Mechanical, And Precision Technologies And Production',
    6099: 'Miscellaneous Fine Arts',
    2201: 'Cosmetology Services And Culinary Arts',
    5299: 'Miscellaneous Psychology',
    2107: 'Computer Networking And Telecommunications',
    5505: 'International Relations',
    2402: 'Biological Engineering',
    6207: 'Finance',
    3699: 'Miscellaneous Biology',
    6209: 'Human Resources And Personnel Management',
    6102: 'Communication Disorders Sciences And Services',
    6103: 'Health And Medical Administrative Services',
    5401: 'Public Administration',
    5006: 'Oceanography',
    5402: 'Public Policy',
    6110: 'Community And Public Health',
    2301: 'Educational Administration And Supervision',
    2309: 'Secondary Teacher Education',
    2308: 'Science And Computer Teacher Education',
    6000: 'Fine Arts',
    1103: 'Animal Sciences',
    2313: 'Language And Drama Education',
    3402: 'Humanities',
    1901: 'Communications',
    5201: 'Educational Psychology',
    0: 'N/A (Less Than Bachelor\'s Degree)',
    1199: 'Miscellaneous Agriculture',
    6006: 'Art History And Criticism',
    2100: 'Computer And Information Systems',
    2102: 'Computer Science',
    1302: 'Forestry',
    3601: 'Biochemical Sciences',
    1301: 'Environmental Science',
    3202: 'Pre-Law And Legal Studies',
    3605: 'Genetics',
    5000: 'Physical Sciences',
    6205: 'Business Economics',
    2407: 'Computer Engineering',
    2406: 'Civil Engineering',
    5098: 'Multi-Disciplinary Or General Science',
    5301: 'Criminal Justice And Fire Protection',
    2307: 'Early Childhood Education',
    6001: 'Drama And Theater Arts',
    1106: 'Soil Science',
    1104: 'Food Science',
    1100: 'General Agriculture',
    2310: 'Special Needs Education',
    1904: 'Advertising And Public Relations',
    3801: 'Military Technologies',
    5200: 'Psychology',
    6007: 'Studio Arts',
    3701: 'Applied Mathematics',
    2504: 'Mechanical Engineering Related Technologies',
    2503: 'Industrial Production Technologies',
    2106: 'Computer Administration Management And Security',
    4005: 'Mathematics And Computer Science',
    6200: 'General Business',
    2001: 'Communication Technologies',
    3604: 'Ecology',
    3608: 'Physiology',
    3607: 'Pharmacology',
    3606: 'Microbiology',
    6210: 'International Business',
    6212: 'Management Information Systems And Statistics',
    5002: 'Atmospheric Sciences And Meteorology',
    6299: 'Miscellaneous Business and Medical Administration',
    2416: 'Mining And Mineral Engineering',
    5008: 'Materials Science',
    2418: 'Nuclear Engineering',
    2417: 'Naval Architecture And Marine Engineering',
    2305: 'Mathematics Teacher Education',
    2304: 'Elementary Education',
    6106: 'Health And Medical Preparatory Programs',
    6105: 'Medical Technologies Technicians',
    6108: 'Pharmacy Pharmaceutical Sciences And Administration',
    6109: 'Treatment Therapy Professions',
    6004: 'Commercial Art And Graphic Design',
    6403: 'United States History',
    5601: 'Construction Services',
    5206: 'Social Psychology',
    3602: 'Botany',
    2599: 'Miscellaneous Engineering Technologies',
    3609: 'Zoology',
    5503: 'Criminology',
    5001: 'Astronomy And Astrophysics',
    6211: 'Hospitality Management',
    5004: 'Geology And Earth Science',
    3611: 'Neuroscience',
    2409: 'Engineering Mechanics Physics And Science',
    6199: 'Miscellaneous Health Medical Professions',
    6002: 'Music',
    6005: 'Film Video And Photographic Arts',
    1105: 'Plant Science And Agronomy',
    1501: 'Area Ethnic And Civilization Studies',
    2312: 'Teacher Education: Multiple Levels',
    1101: 'Agriculture Production And Management',
    2311: 'Social Science Or History Teacher Education',
    1902: 'Journalism',
    2601: 'Linguistics And Comparative Language And Literature',
    6402: 'History',
    4901: 'Theology And Religious Vocations',
    4002: 'Nutrition Sciences',
    5203: 'Counseling Psychology',
    3702: 'Statistics And Decision Science',
    5102: 'Nuclear, Industrial Radiology, And Biological Technologies',
    2502: 'Electrical Engineering Technology',
    2501: 'Engineering And Industrial Management',
    4007: 'Interdisciplinary Social Sciences',
    5502: 'Anthropology And Archeology',
    5901: 'Transportation Sciences And Technologies',
    2405: 'Chemical Engineering',
    2404: 'Biomedical Engineering',
    6104: 'Medical Assisting Services',
    2413: 'Materials Engineering And Materials Science',
    2499: 'Miscellaneous Engineering',
    5005: 'Geosciences',
    2419: 'Petroleum Engineering'
}


sex = {
    1: 'Male', 2: 'Female'
}

when_last_worked = {
    2: '1-5 years ago',
    1: 'Within the past 12 months',
    0: 'N/A (less than 16 years old)',
    3: 'Over 5 years ago or never worked'
}


# Funksjon for å mappe verdier spesifisert i dictionary
def map_values(df, column_name, mapping_dict):
    df[column_name] = df[column_name].map(mapping_dict)
    return df

# Leser inn dataen
df = pd.read_csv(input_file_path)

# Rydder kolonnenavnene
df.columns = df.columns.str.strip().str.replace('\n', '').str.lower()
print(df.columns.tolist())  # Check the cleaned column names

# Filtrerer kolonnene og fyller NA-verdier med 0 før konvertering til int
filtered_df = df[columns_to_keep].fillna(0).astype(int)

# Fører inn verdier fra dictionaryene til riktig kolonne
filtered_df = map_values(filtered_df, 'education_level_id', education_level)
filtered_df = map_values(filtered_df, 'current_education_id', current_education)
filtered_df = map_values(filtered_df, 'field_of_degree1_id', field_of_degree1)
filtered_df = map_values(filtered_df, 'field_of_degree2_id', field_of_degree2)
filtered_df = map_values(filtered_df, 'sex_id', sex)
filtered_df = map_values(filtered_df, 'when_last_worked_id', when_last_worked)

# Sørger for at alle rader har en unik ID
filtered_df.insert(0, 'ID', range(1, len(filtered_df) + 1))

# Lagrer den modifiserte filen
filtered_df.to_csv(output_file_path, index=False)

print(f"Filtrert og konvertert data er lagret til {output_file_path}")